### ISSUE TITLE
Piano evaluation

### ISSUE THREAD

**Issue by enkeejunior1** [andrew-cr/tauLDR#8]
Hi, thank you for your awesome work.

Could you tell me the number of conditional tokens used in the piano evaluation? In the paper's example, it seems to be 32 tokens (2 bars), but in the notebook, it appears to be 8 tokens (1/2 bar), so I'm asking about this.

I'll wait for your answer. Thank you in advance.

**Comment by andrew-cr** [comment]
Hi, thank you for the interest in the work.

I believe it is still 32 tokens conditioning information in the notebook. The conditioning dimension is taken from 
```
condition_dim = eval_cfg.sampler.condition_dim
```
which is 32 in 
```
config/eval/piano.py
```
The `test_data_idx` is 8 and this is just to pick a nice visualization but doesn't affect the conditioning dimension.

**Comment by enkeejunior1** [comment]
Thank you for your prompt response.
